name: Python application test

on: [push, pull_request]

jobs:
  test_web_chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12.1', '3.11.7']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Installing all necessary packages
      run: pip install -r requirements.txt

    - name: GUI tests
      run: pytest tests/test_web.py
